In [1]:
import numpy as np

New arrays can be made in several ways. We can take an existing list and convert it to a numpy array:

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
a = np.zeros((2,2))

In [7]:
a

array([[0., 0.],
       [0., 0.]])

In [9]:
a = np.ones((3,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
A = np.arange(9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
print(A[0]) # Access the first row of A
print(A[0, 1]) # Access the second item of the first row
print(A[:, 1]) # Access the second column

[0 1 2]
1
[1 4 7]


In [15]:
a[:,1]

array([1., 1., 1.])

In [17]:
a = np.array([[1,2], 
              [2,3]])
b = np.array([[4,5],
              [6,7]])

In [18]:
a+b

array([[ 5,  7],
       [ 8, 10]])

In [19]:
a-b

array([[-3, -3],
       [-4, -4]])

In [20]:
a*b   #its not the true multiplication of matrices.Its and multiplication of corresponding elements.

array([[ 4, 10],
       [12, 21]])

In [21]:
print(a / b)

[[0.25       0.4       ]
 [0.33333333 0.42857143]]


In [22]:
print(a**2)

[[1 4]
 [4 9]]


In [29]:
np.sum(a,axis = 0)

array([3, 5])

<h1>Linear Algebra</h1>

In this course, we use the numpy arrays for linear algebra.
We usually use 1D arrays to represent vectors and 2D arrays to represent
matrices

In [30]:
A = np.array([[2,4], 
             [6,8]])

You can take transposes of matrices with `A.T`

In [31]:
print('A\n', A)
print('A.T\n', A.T)

A
 [[2 4]
 [6 8]]
A.T
 [[2 6]
 [4 8]]


## Dot Product 

In [33]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.dot(x,y)

32

In [38]:
A = np.eye(3) ##### Identity matrix
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
B = np.random.randn(3,3)
B

array([[ 0.44821601,  0.35522433,  0.8983292 ],
       [ 0.17816106,  0.03678953,  0.24934615],
       [-0.43191447,  0.00509776,  0.12532008]])

In [51]:
x = np.array([1,2,3]) 
x

array([1, 2, 3])

In [55]:
A @ B   #### matrix multiplications

array([[ 0.44821601,  0.35522433,  0.8983292 ],
       [ 0.17816106,  0.03678953,  0.24934615],
       [-0.43191447,  0.00509776,  0.12532008]])

In [56]:
A @ x    ### maxtrix vector multiplication

array([1., 2., 3.])

Sometimes, we might want to compute certain properties of the matrices. For example, we might be interested in a matrix's determinant, eigenvalues/eigenvectors. Numpy ships with the `numpy.linalg` package to do
these things on 2D arrays (matrices).

In [57]:
from numpy import linalg

In [58]:
linalg.det(A)

1.0

In [59]:
# This computes the eigenvalues and eigenvectors
eigenvalues, eigenvectors = linalg.eig(A)
print("The eigenvalues are\n", eigenvalues)
print("The eigenvectors are\n", eigenvectors)

The eigenvalues are
 [1. 1. 1.]
The eigenvectors are
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Miscellaneous

### Time your code
One tip that is really useful is to use the magic commannd `%time` to time the execution time of your function.

In [60]:
%time np.abs(A)

CPU times: user 15 µs, sys: 2 µs, total: 17 µs
Wall time: 21.5 µs


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
%time linalg.eig(A)

CPU times: user 151 µs, sys: 19 µs, total: 170 µs
Wall time: 176 µs


(array([1., 1., 1.]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))